version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: banco_db
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: JhairV2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  internal_bank_network:
    driver: bridge